# check-status.yml
---
- name: Services Status
  hosts: webserver:loadbalancer
  become: true
  tasks:
  - name: Check status of apache
    shell:
      cmd: service httpd status
      warn: False